on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-14'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install dev dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libpng-dev libjpeg-dev libsqlite3-dev
      - name: Install dev dependencies (macOS)
        if: matrix.os == 'macos-14'
        run: brew install libpng jpeg sqlite3 imagemagick
      - name: Install dependencies
        run: bundle install
      - name: Compile
        run: bundle exec rake compile
      - name: Post-Compile
        if: failure()
        run: cat ext/phashion_ext/mkmf.log
      - name: Run tests
        run: bundle exec rake